engines:
 eslint:
   enabled: true
   channel: "eslint-2"
   config:
   extensions:
   - .es6
   - .js
   - .jsx
 duplication:
   enabled: true
   checks:
     Similar code:
       enabled: false
       Identical code:
   config:
     languages:
     - javascript
ratings:
 paths:
 - src/inverted-index.js
exclude_paths:
- "jasmine/lib/"
- gulpfile.js
- karma.conf.js
- jasmine/build/bundle.js
- src/js/app.js

